#python /data2/tianang/projects/mdlm/synergy_Evo_train_new_reg_MDLM_one_base_model_all_data_classification.py -d 0
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=256 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=260 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=264 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=268 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=272 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=276 classifier_backbone=dit_reg_cls_AMP
CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=280 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=284 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=288 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=292 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=296 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=300 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=304 classifier_backbone=dit_reg_cls_AMP
CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=308 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=312 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=316 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=320 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=324 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=328 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=332 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=336 classifier_backbone=dit_reg_cls_AMP
CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=340 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=344 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=348 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=352 classifier_backbone=dit_reg_cls_AMP
CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=356 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=360 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=364 classifier_backbone=dit_reg_cls_AMP
CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=368 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=372 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=376 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=380 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=384 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=388 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=392 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=396 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=400 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=404 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=408 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=412 classifier_backbone=dit_reg_cls_AMP
#CUDA_VISIBLE_DEVICES=2 python ../main.py sampling.strain=47085 sampling.target_MIC=1 sampling.target_length=416 classifier_backbone=dit_reg_cls_AMP
